import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "../globals.css";

import Footer from "../Components/userpanel/Footer";
import Header from "../Components/userpanel/Header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head> 
      <link href="https://fonts.googleapis.com/css?family=Poppins:400,600|Roboto:400,400i,500" rel="stylesheet"/>
 
	<link rel="stylesheet" href="/css/linearicons.css"/>
	<link rel="stylesheet" href="/css/font-awesome.min.css"/>
	<link rel="stylesheet" href="/css/bootstrap.css"/>
	<link rel="stylesheet" href="/css/magnific-popup.css"/>
	<link rel="stylesheet" href="/css/nice-select.css"/>
	<link rel="stylesheet" href="/css/hexagons.min.css"/>
	<link rel="stylesheet" href="/css/owl.carousel.css"/>
	<link rel="stylesheet" href="/css/main.css"></link>
  </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
         <Toaster position="top-right" />
         <Header/>
        {children}
       
        <script src="/js/vendor/jquery-2.2.4.min.js"></script>
 
 <script src="/js/tilt.jquery.min.js"></script>
 	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	 crossOrigin="anonymous"></script>
 <script src="/js/vendor/bootstrap.min.js"></script>
 <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
 <script src="/js/easing.min.js"></script>
 <script src="js/hoverIntent.js"></script>
 <script src="/js/superfish.min.js"></script>
 <script src="/js/jquery.ajaxchimp.min.js"></script>
 <script src="/js/jquery.magnific-popup.min.js"></script>
 <script src="/js/owl.carousel.min.js"></script>
 <script src="/js/owl-carousel-thumb.min.js"></script>
 <script src="/js/hexagons.min.js"></script>
 <script src="/js/jquery.nice-select.min.js"></script>
 <script src="/js/waypoints.min.js"></script>
 <script src="/js/mail-script.js"></script>
 <script src="/js/main.js"></script>
      </body>

    

    </html>
  );
}
